{"text": "September 22, 2025 > 08:37:40 | INFO | GET /\n", "record": {"elapsed": {"repr": "0:00:15.506013", "seconds": 15.506013}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/", "headers": "Headers({'host': '192.168.0.13:8000', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'cookie': 'stitch_admin_pin=MjgzOTE3; access_token=\"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTc3NDY4MTQsInN1YiI6IjEiLCJzY29wZSI6ImFjYyBhcGkgYXBpOnIgdXNyIHVzcjpyIGFkbWluIGFwcCBhcHA6ciBwcm9kIn0.LwkClv7QQuZF2mWhQUC0MCfusKkVSwQkYCPnuI1-dyI\"', 'upgrade-insecure-requests': '1', 'priority': 'u=0, i'})", "method": "GET"}, "res": {"status_code": 404}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "GET /", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 38, "name": "MainProcess"}, "thread": {"id": 139997720987328, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-22 08:37:40.241599+00:00", "timestamp": 1758530260.241599}}}
{"text": "September 22, 2025 > 08:37:40 | INFO | GET /favicon.ico\n", "record": {"elapsed": {"repr": "0:00:15.530432", "seconds": 15.530432}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/favicon.ico", "headers": "Headers({'host': '192.168.0.13:8000', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'image/avif,image/webp,image/png,image/svg+xml,image/*;q=0.8,*/*;q=0.5', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'referer': 'http://192.168.0.13:8000/', 'priority': 'u=6'})", "method": "GET"}, "res": {"status_code": 404}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "GET /favicon.ico", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 38, "name": "MainProcess"}, "thread": {"id": 139997720987328, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-22 08:37:40.266018+00:00", "timestamp": 1758530260.266018}}}
{"text": "September 22, 2025 > 08:37:45 | INFO | GET /docs\n", "record": {"elapsed": {"repr": "0:00:20.268580", "seconds": 20.26858}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/docs", "headers": "Headers({'host': '192.168.0.13:8000', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'cookie': 'stitch_admin_pin=MjgzOTE3; access_token=\"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTc3NDY4MTQsInN1YiI6IjEiLCJzY29wZSI6ImFjYyBhcGkgYXBpOnIgdXNyIHVzcjpyIGFkbWluIGFwcCBhcHA6ciBwcm9kIn0.LwkClv7QQuZF2mWhQUC0MCfusKkVSwQkYCPnuI1-dyI\"', 'upgrade-insecure-requests': '1', 'priority': 'u=0, i'})", "method": "GET"}, "res": {"status_code": 404}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "GET /docs", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 38, "name": "MainProcess"}, "thread": {"id": 139997720987328, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-22 08:37:45.004166+00:00", "timestamp": 1758530265.004166}}}
{"text": "September 22, 2025 > 08:38:02 | DEBUG | GET /backend/docs\n", "record": {"elapsed": {"repr": "0:00:37.838844", "seconds": 37.838844}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/docs", "headers": "Headers({'host': '192.168.0.13:8000', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'cookie': 'stitch_admin_pin=MjgzOTE3; access_token=\"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTc3NDY4MTQsInN1YiI6IjEiLCJzY29wZSI6ImFjYyBhcGkgYXBpOnIgdXNyIHVzcjpyIGFkbWluIGFwcCBhcHA6ciBwcm9kIn0.LwkClv7QQuZF2mWhQUC0MCfusKkVSwQkYCPnuI1-dyI\"', 'upgrade-insecure-requests': '1', 'priority': 'u=0, i'})", "method": "GET"}, "res": {"status_code": 200}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "🐞", "name": "DEBUG", "no": 10}, "line": 49, "message": "GET /backend/docs", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 38, "name": "MainProcess"}, "thread": {"id": 139997720987328, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-22 08:38:02.574430+00:00", "timestamp": 1758530282.57443}}}
{"text": "September 22, 2025 > 08:38:03 | DEBUG | GET /backend/openapi.json\n", "record": {"elapsed": {"repr": "0:00:38.693900", "seconds": 38.6939}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/openapi.json", "headers": "Headers({'host': '192.168.0.13:8000', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json,*/*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'referer': 'http://192.168.0.13:8000/backend/docs', 'connection': 'keep-alive', 'cookie': 'stitch_admin_pin=MjgzOTE3; access_token=\"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTc3NDY4MTQsInN1YiI6IjEiLCJzY29wZSI6ImFjYyBhcGkgYXBpOnIgdXNyIHVzcjpyIGFkbWluIGFwcCBhcHA6ciBwcm9kIn0.LwkClv7QQuZF2mWhQUC0MCfusKkVSwQkYCPnuI1-dyI\"', 'priority': 'u=4'})", "method": "GET"}, "res": {"status_code": 200}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "🐞", "name": "DEBUG", "no": 10}, "line": 49, "message": "GET /backend/openapi.json", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 38, "name": "MainProcess"}, "thread": {"id": 139997720987328, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-22 08:38:03.429486+00:00", "timestamp": 1758530283.429486}}}
{"text": "September 22, 2025 > 09:34:36 | INFO | GET /\n", "record": {"elapsed": {"repr": "0:05:43.719011", "seconds": 343.719011}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/", "headers": "Headers({'host': '192.168.0.13:8000', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'connection': 'keep-alive', 'cookie': 'stitch_admin_pin=MjgzOTE3; access_token=\"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTc3NDY4MTQsInN1YiI6IjEiLCJzY29wZSI6ImFjYyBhcGkgYXBpOnIgdXNyIHVzcjpyIGFkbWluIGFwcCBhcHA6ciBwcm9kIn0.LwkClv7QQuZF2mWhQUC0MCfusKkVSwQkYCPnuI1-dyI\"', 'upgrade-insecure-requests': '1', 'priority': 'u=0, i'})", "method": "GET"}, "res": {"status_code": 404}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "GET /", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 10, "name": "MainProcess"}, "thread": {"id": 139839100503744, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-22 09:34:36.797750+00:00", "timestamp": 1758533676.79775}}}
{"text": "September 22, 2025 > 09:37:16 | ERROR | (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation \"accounts\" does not exist\n[SQL: SELECT accounts.id, accounts.name, accounts.password_hash, accounts.created_at, accounts.updated_at \nFROM accounts \nWHERE accounts.name = $1::VARCHAR]\n[parameters: ('ыв',)]\n(Background on this error at: https://sqlalche.me/e/20/f405)\nTraceback (most recent call last):\n\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 521, in _prepare_and_execute\n    prepared_stmt, attributes = await adapt_connection._prepare(\n                                      │                └ <function AsyncAdapt_asyncpg_connection._prepare at 0x7f2ed6353880>\n                                      └ <AdaptedConnection <asyncpg.connection.Connection object at 0x7f2ed5ec36a0>>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 768, in _prepare\n    prepared_stmt = await self._connection.prepare(\n                          │    └ <member '_connection' of 'AdaptedConnection' objects>\n                          └ <AdaptedConnection <asyncpg.connection.Connection object at 0x7f2ed5ec36a0>>\n  File \"/app/.venv/lib/python3.11/site-packages/asyncpg/connection.py\", line 635, in prepare\n    return await self._prepare(\n                 │    └ <function Connection._prepare at 0x7f2ed60e32e0>\n                 └ <asyncpg.connection.Connection object at 0x7f2ed5ec36a0>\n  File \"/app/.venv/lib/python3.11/site-packages/asyncpg/connection.py\", line 653, in _prepare\n    stmt = await self._get_statement(\n                 │    └ <function Connection._get_statement at 0x7f2ed60e2fc0>\n                 └ <asyncpg.connection.Connection object at 0x7f2ed5ec36a0>\n  File \"/app/.venv/lib/python3.11/site-packages/asyncpg/connection.py\", line 432, in _get_statement\n    statement = await self._protocol.prepare(\n                      │    └ <member '_protocol' of 'Connection' objects>\n                      └ <asyncpg.connection.Connection object at 0x7f2ed5ec36a0>\n  File \"asyncpg/protocol/protocol.pyx\", line 165, in prepare\n    return await waiter\n\nasyncpg.exceptions.UndefinedTableError: relation \"accounts\" does not exist\n\n\nThe above exception was the direct cause of the following exception:\n\n\nTraceback (most recent call last):\n\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1967, in _exec_single_context\n    self.dialect.do_execute(\n    │    │       └ <function DefaultDialect.do_execute at 0x7f2ed6b932e0>\n    │    └ <sqlalchemy.dialects.postgresql.asyncpg.PGDialect_asyncpg object at 0x7f2ed6449bd0>\n    └ <sqlalchemy.engine.base.Connection object at 0x7f2ed5f7d950>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py\", line 951, in do_execute\n    cursor.execute(statement, parameters)\n    │      │       │          └ ('ыв',)\n    │      │       └ 'SELECT accounts.id, accounts.name, accounts.password_hash, accounts.created_at, accounts.updated_at \\nFROM accounts \\nWHERE ...\n    │      └ <function AsyncAdapt_asyncpg_cursor.execute at 0x7f2ed6352c00>\n    └ <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_cursor object at 0x7f2ed5f940a0>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 580, in execute\n    self._adapt_connection.await_(\n    │    └ <member '_adapt_connection' of 'AsyncAdapt_asyncpg_cursor' objects>\n    └ <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_cursor object at 0x7f2ed5f940a0>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 132, in await_only\n    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501\n           │       │             └ <coroutine object AsyncAdapt_asyncpg_cursor._prepare_and_execute at 0x7f2ed6153be0>\n           │       └ <attribute 'parent' of 'greenlet.greenlet' objects>\n           └ <_AsyncIoGreenlet object at 0x7f2ed63cf840 (otid=0x7f2ed7622190) dead>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 196, in greenlet_spawn\n    value = await result\n                  └ <coroutine object AsyncAdapt_asyncpg_cursor._prepare_and_execute at 0x7f2ed6153be0>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 558, in _prepare_and_execute\n    self._handle_exception(error)\n    │    └ <function AsyncAdapt_asyncpg_cursor._handle_exception at 0x7f2ed6352a20>\n    └ <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_cursor object at 0x7f2ed5f940a0>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 508, in _handle_exception\n    self._adapt_connection._handle_exception(error)\n    │    │                                   └ UndefinedTableError('relation \"accounts\" does not exist')\n    │    └ <member '_adapt_connection' of 'AsyncAdapt_asyncpg_cursor' objects>\n    └ <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_cursor object at 0x7f2ed5f940a0>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 792, in _handle_exception\n    raise translated_error from error\n          │                     └ UndefinedTableError('relation \"accounts\" does not exist')\n          └ ProgrammingError('<class \\'asyncpg.exceptions.UndefinedTableError\\'>: relation \"accounts\" does not exist')\n\nsqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.ProgrammingError: <class 'asyncpg.exceptions.UndefinedTableError'>: relation \"accounts\" does not exist\n\n\nThe above exception was the direct cause of the following exception:\n\n\nTraceback (most recent call last):\n\n  File \"/app/.venv/bin/uvicorn\", line 10, in <module>\n    sys.exit(main())\n    │   │    └ <Command main>\n    │   └ <built-in function exit>\n    └ <module 'sys' (built-in)>\n  File \"/app/.venv/lib/python3.11/site-packages/click/core.py\", line 1462, in __call__\n    return self.main(*args, **kwargs)\n           │    │     │       └ {}\n           │    │     └ ()\n           │    └ <function Command.main at 0x7f2ed893bb00>\n           └ <Command main>\n  File \"/app/.venv/lib/python3.11/site-packages/click/core.py\", line 1383, in main\n    rv = self.invoke(ctx)\n         │    │      └ <click.core.Context object at 0x7f2ed98498d0>\n         │    └ <function Command.invoke at 0x7f2ed893b7e0>\n         └ <Command main>\n  File \"/app/.venv/lib/python3.11/site-packages/click/core.py\", line 1246, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n           │   │      │    │           │   └ {'host': '0.0.0.0', 'port': 8000, 'app': 'src.main:app', 'uds': None, 'fd': None, 'reload': False, 'reload_dirs': (), 'reload...\n           │   │      │    │           └ <click.core.Context object at 0x7f2ed98498d0>\n           │   │      │    └ <function main at 0x7f2ed85149a0>\n           │   │      └ <Command main>\n           │   └ <function Context.invoke at 0x7f2ed893aa20>\n           └ <click.core.Context object at 0x7f2ed98498d0>\n  File \"/app/.venv/lib/python3.11/site-packages/click/core.py\", line 814, in invoke\n    return callback(*args, **kwargs)\n           │         │       └ {'host': '0.0.0.0', 'port': 8000, 'app': 'src.main:app', 'uds': None, 'fd': None, 'reload': False, 'reload_dirs': (), 'reload...\n           │         └ ()\n           └ <function main at 0x7f2ed85149a0>\n  File \"/app/.venv/lib/python3.11/site-packages/uvicorn/main.py\", line 415, in main\n    run(\n    └ <function run at 0x7f2ed87d27a0>\n  File \"/app/.venv/lib/python3.11/site-packages/uvicorn/main.py\", line 582, in run\n    server.run()\n    │      └ <function Server.run at 0x7f2ed87d2020>\n    └ <uvicorn.server.Server object at 0x7f2ed8836290>\n  File \"/app/.venv/lib/python3.11/site-packages/uvicorn/server.py\", line 67, in run\n    return asyncio_run(self.serve(sockets=sockets), loop_factory=self.config.get_loop_factory())\n           │           │    │             │                      │    │      └ <function Config.get_loop_factory at 0x7f2ed89722a0>\n           │           │    │             │                      │    └ <uvicorn.config.Config object at 0x7f2ed984a150>\n           │           │    │             │                      └ <uvicorn.server.Server object at 0x7f2ed8836290>\n           │           │    │             └ None\n           │           │    └ <function Server.serve at 0x7f2ed87d20c0>\n           │           └ <uvicorn.server.Server object at 0x7f2ed8836290>\n           └ <function asyncio_run at 0x7f2ed87d1f80>\n  File \"/app/.venv/lib/python3.11/site-packages/uvicorn/_compat.py\", line 23, in asyncio_run\n    return runner.run(main)\n           │      │   └ <coroutine object Server.serve at 0x7f2ed86e4130>\n           │      └ <function Runner.run at 0x7f2ed8b90220>\n           └ <asyncio.runners.Runner object at 0x7f2ed9a8bd50>\n  File \"/usr/local/lib/python3.11/asyncio/runners.py\", line 118, in run\n    return self._loop.run_until_complete(task)\n           │    │     │                  └ <Task pending name='Task-1' coro=<Server.serve() running at /app/.venv/lib/python3.11/site-packages/uvicorn/server.py:71> wai...\n           │    │     └ <cyfunction Loop.run_until_complete at 0x7f2ed87075e0>\n           │    └ <uvloop.Loop running=True closed=False debug=False>\n           └ <asyncio.runners.Runner object at 0x7f2ed9a8bd50>\n  File \"/app/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py\", line 409, in run_asgi\n    result = await app(  # type: ignore[func-returns-value]\n                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f2ed85627d0>\n  File \"/app/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py\", line 60, in __call__\n    return await self.app(scope, receive, send)\n                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f2ed5ea7a...\n                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f2ed5e...\n                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.21.0.3', 8000), 'c...\n                 │    └ <fastapi.applications.FastAPI object at 0x7f2ed7fc8990>\n                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f2ed85627d0>\n  File \"/app/.venv/lib/python3.11/site-packages/fastapi/applications.py\", line 1082, in __call__\n    await super().__call__(scope, receive, send)\n                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f2ed5ea7a...\n                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f2ed5e...\n                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.21.0.3', 8000), 'c...\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/applications.py\", line 113, in __call__\n    await self.middleware_stack(scope, receive, send)\n          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f2ed5ea7a...\n          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f2ed5e...\n          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.21.0.3', 8000), 'c...\n          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f2ed6613e10>\n          └ <fastapi.applications.FastAPI object at 0x7f2ed7fc8990>\n> File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py\", line 164, in __call__\n    await self.app(scope, receive, _send)\n          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7f2ed5f745e0>\n          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f2ed5e...\n          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.21.0.3', 8000), 'c...\n          │    └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f2ed9618a50>\n          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f2ed6613e10>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 182, in __call__\n    with recv_stream, send_stream, collapse_excgroups():\n         │            │            └ <function collapse_excgroups at 0x7f2ed77791c0>\n         │            └ MemoryObjectSendStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_receive...\n         └ MemoryObjectReceiveStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_rece...\n  File \"/usr/local/lib/python3.11/contextlib.py\", line 158, in __exit__\n    self.gen.throw(typ, value, traceback)\n    │    │   │     │    │      └ <traceback object at 0x7f2ed5f92480>\n    │    │   │     │    └ ExceptionGroup('unhandled errors in a TaskGroup', [ProgrammingError('(sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError...\n    │    │   │     └ <class 'ExceptionGroup'>\n    │    │   └ <method 'throw' of 'generator' objects>\n    │    └ <generator object collapse_excgroups at 0x7f2ed5f5a180>\n    └ <contextlib._GeneratorContextManager object at 0x7f2ed5ea7990>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/_utils.py\", line 85, in collapse_excgroups\n    raise exc\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 184, in __call__\n    response = await self.dispatch_func(request, call_next)\n                     │    │             │        └ <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x7f2ed5f74680>\n                     │    │             └ <starlette.middleware.base._CachedRequest object at 0x7f2ed5ea7c10>\n                     │    └ <function setup_fastapi_logging.<locals>.log_request at 0x7f2ed5f3cd60>\n                     └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f2ed9618a50>\n\n  File \"/app/src/core/logging_setup.py\", line 53, in log_request\n    response: Response = await call_next(request)\n                               │         └ <starlette.middleware.base._CachedRequest object at 0x7f2ed5ea7c10>\n                               └ <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x7f2ed5f74680>\n\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 159, in call_next\n    raise app_exc\n          └ ProgrammingError('(sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class \\'asyncpg.exceptions.UndefinedTableError\\'...\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n          │    │   │      │                      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.send_no_error at 0x7f2ed5f759e0>\n          │    │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f2ed5f75a80>\n          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.21.0.3', 8000), 'c...\n          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f2ed656c490>\n          └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f2ed9618a50>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n          │                            │    │    │     │      │        └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.send_no_error at 0x7f2ed5f759e0>\n          │                            │    │    │     │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f2ed5f75a80>\n          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.21.0.3', 8000), 'c...\n          │                            │    │    └ <starlette.requests.Request object at 0x7f2ed5ea7dd0>\n          │                            │    └ <fastapi.routing.APIRouter object at 0x7f2ed5f69c90>\n          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f2ed656c490>\n          └ <function wrap_app_handling_exceptions at 0x7f2ed75efd80>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7f2ed5f75760>\n          │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f2ed5f75a80>\n          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.21.0.3', 8000), 'c...\n          └ <fastapi.routing.APIRouter object at 0x7f2ed5f69c90>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7f2ed5f75760>\n          │    │                │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f2ed5f75a80>\n          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.21.0.3', 8000), 'c...\n          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x7f2ed5f69c90>>\n          └ <fastapi.routing.APIRouter object at 0x7f2ed5f69c90>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7f2ed5f75760>\n          │     │      │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f2ed5f75a80>\n          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.21.0.3', 8000), 'c...\n          │     └ <function Route.handle at 0x7f2ed76313a0>\n          └ APIRoute(path='/backend/auth/login', name='login_account', methods=['POST'])\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7f2ed5f75760>\n          │    │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f2ed5f75a80>\n          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.21.0.3', 8000), 'c...\n          │    └ <function request_response.<locals>.app at 0x7f2ed5f3d260>\n          └ APIRoute(path='/backend/auth/login', name='login_account', methods=['POST'])\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7f2ed5f75760>\n          │                            │    │        │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f2ed5f75a80>\n          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.21.0.3', 8000), 'c...\n          │                            │    └ <starlette.requests.Request object at 0x7f2ed5ea7f10>\n          │                            └ <function request_response.<locals>.app.<locals>.app at 0x7f2ed5f756c0>\n          └ <function wrap_app_handling_exceptions at 0x7f2ed75efd80>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7f2ed5f75580>\n          │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f2ed5f75a80>\n          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.21.0.3', 8000), 'c...\n          └ <function request_response.<locals>.app.<locals>.app at 0x7f2ed5f756c0>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 75, in app\n    response = await f(request)\n                     │ └ <starlette.requests.Request object at 0x7f2ed5ea7f10>\n                     └ <function get_request_handler.<locals>.app at 0x7f2ed5f3d300>\n  File \"/app/.venv/lib/python3.11/site-packages/fastapi/routing.py\", line 308, in app\n    raw_response = await run_endpoint_function(\n                         └ <function run_endpoint_function at 0x7f2ed7630ea0>\n  File \"/app/.venv/lib/python3.11/site-packages/fastapi/routing.py\", line 219, in run_endpoint_function\n    return await dependant.call(**values)\n                 │         │      └ {'auth_uow': <src.auth.infrastructure.db.unit_of_work.PGAuthUnitOfWork object at 0x7f2ed5ea6f50>, 'password_helper': <src.aut...\n                 │         └ <function login_account at 0x7f2ed61627a0>\n                 └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[], dependencies=[Dependant(path_p...\n\n  File \"/app/src/auth/api/rest.py\", line 24, in login_account\n    return await LoginUseCase(auth_uow, auth_provider, password_helper).execute(dto)\n                 │            │         │              │                        └ LoginDTO(name='ыв', password='ыв')\n                 │            │         │              └ <src.auth.infrastructure.password_helper.PasswordHelper object at 0x7f2ed5f7c450>\n                 │            │         └ <src.auth.infrastructure.jwt_auth_provider.JWTAuthProvider object at 0x7f2ed5f7c3d0>\n                 │            └ <src.auth.infrastructure.db.unit_of_work.PGAuthUnitOfWork object at 0x7f2ed5ea6f50>\n                 └ <class 'src.auth.application.use_cases.login.LoginUseCase'>\n\n  File \"/app/src/auth/application/use_cases/login.py\", line 20, in execute\n    account = await self.auth_uow.accounts.get_by_name(dto.name)\n                    │    │        │        │           │   └ 'ыв'\n                    │    │        │        │           └ LoginDTO(name='ыв', password='ыв')\n                    │    │        │        └ <function PGAccountRepository.get_by_name at 0x7f2ed6beda80>\n                    │    │        └ <src.core.account.repository.PGAccountRepository object at 0x7f2ed5f7c910>\n                    │    └ <src.auth.infrastructure.db.unit_of_work.PGAuthUnitOfWork object at 0x7f2ed5ea6f50>\n                    └ <src.auth.application.use_cases.login.LoginUseCase object at 0x7f2ed5edb0d0>\n\n  File \"/app/src/core/account/repository.py\", line 23, in get_by_name\n    model = await self.session.scalar(query)\n                  │    │       │      └ <sqlalchemy.sql.selectable.Select object at 0x7f2ed640c610>\n                  │    │       └ <function AsyncSession.scalar at 0x7f2ed67d4680>\n                  │    └ <sqlalchemy.ext.asyncio.session.AsyncSession object at 0x7f2ed5f7c410>\n                  └ <src.core.account.repository.PGAccountRepository object at 0x7f2ed5f7c910>\n\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py\", line 519, in scalar\n    return await greenlet_spawn(\n                 └ <function greenlet_spawn at 0x7f2ed74a67a0>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 201, in greenlet_spawn\n    result = context.throw(*sys.exc_info())\n             │       │      │   └ <built-in function exc_info>\n             │       │      └ <module 'sys' (built-in)>\n             │       └ <method 'throw' of 'greenlet.greenlet' objects>\n             └ <_AsyncIoGreenlet object at 0x7f2ed63cf840 (otid=0x7f2ed7622190) dead>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py\", line 2413, in scalar\n    return self._execute_internal(\n           │    └ <function Session._execute_internal at 0x7f2ed68fee80>\n           └ <sqlalchemy.orm.session.Session object at 0x7f2ed5f7c350>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py\", line 2251, in _execute_internal\n    result: Result[Any] = compile_state_cls.orm_execute_statement(\n                   │      │                 └ <classmethod(<function AbstractORMCompileState.orm_execute_statement at 0x7f2ed6949c60>)>\n                   │      └ <class 'sqlalchemy.orm.context.ORMSelectCompileState'>\n                   └ typing.Any\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/orm/context.py\", line 306, in orm_execute_statement\n    result = conn.execute(\n             │    └ <function Connection.execute at 0x7f2ed6ce7600>\n             └ <sqlalchemy.engine.base.Connection object at 0x7f2ed5f7d950>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1419, in execute\n    return meth(\n           └ <bound method ClauseElement._execute_on_connection of <sqlalchemy.sql.selectable.Select object at 0x7f2ed640c610>>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py\", line 526, in _execute_on_connection\n    return connection._execute_clauseelement(\n           │          └ <function Connection._execute_clauseelement at 0x7f2ed6ce7920>\n           └ <sqlalchemy.engine.base.Connection object at 0x7f2ed5f7d950>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1641, in _execute_clauseelement\n    ret = self._execute_context(\n          │    └ <function Connection._execute_context at 0x7f2ed6ce7b00>\n          └ <sqlalchemy.engine.base.Connection object at 0x7f2ed5f7d950>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1846, in _execute_context\n    return self._exec_single_context(\n           │    └ <function Connection._exec_single_context at 0x7f2ed6ce7ba0>\n           └ <sqlalchemy.engine.base.Connection object at 0x7f2ed5f7d950>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1986, in _exec_single_context\n    self._handle_dbapi_exception(\n    │    └ <function Connection._handle_dbapi_exception at 0x7f2ed6ce7e20>\n    └ <sqlalchemy.engine.base.Connection object at 0x7f2ed5f7d950>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 2355, in _handle_dbapi_exception\n    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n          │                    │              │                 └ ProgrammingError('<class \\'asyncpg.exceptions.UndefinedTableError\\'>: relation \"accounts\" does not exist')\n          │                    │              └ (<class 'sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.ProgrammingError'>, ProgrammingError('<class \\'async...\n          │                    └ <method 'with_traceback' of 'BaseException' objects>\n          └ ProgrammingError('(sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class \\'asyncpg.exceptions.UndefinedTableError\\'...\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py\", line 1967, in _exec_single_context\n    self.dialect.do_execute(\n    │    │       └ <function DefaultDialect.do_execute at 0x7f2ed6b932e0>\n    │    └ <sqlalchemy.dialects.postgresql.asyncpg.PGDialect_asyncpg object at 0x7f2ed6449bd0>\n    └ <sqlalchemy.engine.base.Connection object at 0x7f2ed5f7d950>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py\", line 951, in do_execute\n    cursor.execute(statement, parameters)\n    │      │       │          └ ('ыв',)\n    │      │       └ 'SELECT accounts.id, accounts.name, accounts.password_hash, accounts.created_at, accounts.updated_at \\nFROM accounts \\nWHERE ...\n    │      └ <function AsyncAdapt_asyncpg_cursor.execute at 0x7f2ed6352c00>\n    └ <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_cursor object at 0x7f2ed5f940a0>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 580, in execute\n    self._adapt_connection.await_(\n    │    └ <member '_adapt_connection' of 'AsyncAdapt_asyncpg_cursor' objects>\n    └ <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_cursor object at 0x7f2ed5f940a0>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 132, in await_only\n    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501\n           │       │             └ <coroutine object AsyncAdapt_asyncpg_cursor._prepare_and_execute at 0x7f2ed6153be0>\n           │       └ <attribute 'parent' of 'greenlet.greenlet' objects>\n           └ <_AsyncIoGreenlet object at 0x7f2ed63cf840 (otid=0x7f2ed7622190) dead>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py\", line 196, in greenlet_spawn\n    value = await result\n                  └ <coroutine object AsyncAdapt_asyncpg_cursor._prepare_and_execute at 0x7f2ed6153be0>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 558, in _prepare_and_execute\n    self._handle_exception(error)\n    │    └ <function AsyncAdapt_asyncpg_cursor._handle_exception at 0x7f2ed6352a20>\n    └ <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_cursor object at 0x7f2ed5f940a0>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 508, in _handle_exception\n    self._adapt_connection._handle_exception(error)\n    │    │                                   └ UndefinedTableError('relation \"accounts\" does not exist')\n    │    └ <member '_adapt_connection' of 'AsyncAdapt_asyncpg_cursor' objects>\n    └ <sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_cursor object at 0x7f2ed5f940a0>\n  File \"/app/.venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py\", line 792, in _handle_exception\n    raise translated_error from error\n          │                     └ UndefinedTableError('relation \"accounts\" does not exist')\n          └ ProgrammingError('<class \\'asyncpg.exceptions.UndefinedTableError\\'>: relation \"accounts\" does not exist')\n\nsqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation \"accounts\" does not exist\n[SQL: SELECT accounts.id, accounts.name, accounts.password_hash, accounts.created_at, accounts.updated_at \nFROM accounts \nWHERE accounts.name = $1::VARCHAR]\n[parameters: ('ыв',)]\n(Background on this error at: https://sqlalche.me/e/20/f405)\n", "record": {"elapsed": {"repr": "0:08:23.653506", "seconds": 503.653506}, "exception": {"type": "ProgrammingError", "value": "(sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation \"accounts\" does not exist\n[SQL: SELECT accounts.id, accounts.name, accounts.password_hash, accounts.created_at, accounts.updated_at \nFROM accounts \nWHERE accounts.name = $1::VARCHAR]\n[parameters: ('ыв',)]\n(Background on this error at: https://sqlalche.me/e/20/f405)", "traceback": true}, "extra": {"name": "fastapi", "app_name": "Pool"}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log_exceptions", "level": {"icon": "❌", "name": "ERROR", "no": 40}, "line": 59, "message": "(sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation \"accounts\" does not exist\n[SQL: SELECT accounts.id, accounts.name, accounts.password_hash, accounts.created_at, accounts.updated_at \nFROM accounts \nWHERE accounts.name = $1::VARCHAR]\n[parameters: ('ыв',)]\n(Background on this error at: https://sqlalche.me/e/20/f405)", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 10, "name": "MainProcess"}, "thread": {"id": 139839197379456, "name": "MainThread"}, "time": {"repr": "2025-09-22 09:37:16.732245+00:00", "timestamp": 1758533836.732245}}}
{"text": "September 22, 2025 > 13:14:32 | INFO | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:09:55.853810", "seconds": 595.85381}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': 'localhost:8000', 'user-agent': 'curl/7.81.0', 'accept': '*/*', 'content-type': 'application/json', 'content-length': '81'})", "method": "POST"}, "res": {"status_code": 401}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 10, "name": "MainProcess"}, "thread": {"id": 139962170148544, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-22 13:14:32.376242+00:00", "timestamp": 1758546872.376242}}}
{"text": "September 22, 2025 > 13:15:22 | INFO | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:10:46.115395", "seconds": 646.115395}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': 'localhost:8000', 'user-agent': 'curl/7.81.0', 'accept': '*/*', 'content-type': 'application/json', 'content-length': '81'})", "method": "POST"}, "res": {"status_code": 401}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 10, "name": "MainProcess"}, "thread": {"id": 139962170148544, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-22 13:15:22.637827+00:00", "timestamp": 1758546922.637827}}}
{"text": "September 22, 2025 > 13:16:45 | DEBUG | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:01:08.511750", "seconds": 68.51175}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': 'localhost:8000', 'user-agent': 'curl/7.81.0', 'accept': '*/*', 'content-type': 'application/json', 'content-length': '81'})", "method": "POST"}, "res": {"status_code": 201}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "🐞", "name": "DEBUG", "no": 10}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 10, "name": "MainProcess"}, "thread": {"id": 139927107913408, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-22 13:16:45.939597+00:00", "timestamp": 1758547005.939597}}}
{"text": "September 22, 2025 > 13:30:04 | INFO | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:00:09.781894", "seconds": 9.781894}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': 'localhost:8000', 'user-agent': 'curl/7.81.0', 'accept': '*/*', 'content-type': 'application/json', 'content-length': '81'})", "method": "POST"}, "res": {"status_code": 409}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 29, "name": "SpawnProcess-9"}, "thread": {"id": 140718110398144, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-22 13:30:04.203878+00:00", "timestamp": 1758547804.203878}}}
{"text": "September 22, 2025 > 13:30:13 | DEBUG | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:00:18.636079", "seconds": 18.636079}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': 'localhost:8000', 'user-agent': 'curl/7.81.0', 'accept': '*/*', 'content-type': 'application/json', 'content-length': '82'})", "method": "POST"}, "res": {"status_code": 201}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "🐞", "name": "DEBUG", "no": 10}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 29, "name": "SpawnProcess-9"}, "thread": {"id": 140718110398144, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-22 13:30:13.058063+00:00", "timestamp": 1758547813.058063}}}
{"text": "September 22, 2025 > 13:34:37 | DEBUG | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:00:20.247533", "seconds": 20.247533}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '53', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'application/json', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'cookie': 'stitch_admin_pin=MjgzOTE3; access_token=\"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTc3NDY4MTQsInN1YiI6IjEiLCJzY29wZSI6ImFjYyBhcGkgYXBpOnIgdXNyIHVzcjpyIGFkbWluIGFwcCBhcHA6ciBwcm9kIn0.LwkClv7QQuZF2mWhQUC0MCfusKkVSwQkYCPnuI1-dyI\"', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 201}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "🐞", "name": "DEBUG", "no": 10}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 139625772279488, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-22 13:34:37.789640+00:00", "timestamp": 1758548077.78964}}}
{"text": "September 23, 2025 > 07:22:20 | INFO | POST /backend/auth/login\n", "record": {"elapsed": {"repr": "0:01:02.125938", "seconds": 62.125938}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/login", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '301', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'multipart/form-data; boundary=---------------------------213150106124555115452950345544', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 401}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/login", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 140196513842880, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 07:22:20.818274+00:00", "timestamp": 1758612140.818274}}}
{"text": "September 23, 2025 > 07:22:40 | DEBUG | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:01:22.292702", "seconds": 82.292702}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '52', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'application/json', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 201}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "🐞", "name": "DEBUG", "no": 10}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 140196513842880, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 07:22:40.985038+00:00", "timestamp": 1758612160.985038}}}
{"text": "September 23, 2025 > 07:22:55 | INFO | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:01:36.807237", "seconds": 96.807237}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '50', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'application/json', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 409}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 140196513842880, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 07:22:55.499573+00:00", "timestamp": 1758612175.499573}}}
{"text": "September 23, 2025 > 07:48:18 | INFO | POST /backend/auth/login\n", "record": {"elapsed": {"repr": "0:00:06.869308", "seconds": 6.869308}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/login", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '300', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'multipart/form-data; boundary=---------------------------10476654381336145824137825846', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 401}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/login", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 139840450717376, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 07:48:18.401152+00:00", "timestamp": 1758613698.401152}}}
{"text": "September 23, 2025 > 08:00:14 | INFO | POST /backend/auth/login\n", "record": {"elapsed": {"repr": "0:00:06.789204", "seconds": 6.789204}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/login", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '303', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'multipart/form-data; boundary=---------------------------337833748527148114311822262072', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 401}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/login", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 140094664083136, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 08:00:14.021285+00:00", "timestamp": 1758614414.021285}}}
{"text": "September 23, 2025 > 08:00:21 | INFO | POST /backend/auth/login\n", "record": {"elapsed": {"repr": "0:00:13.813185", "seconds": 13.813185}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/login", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '303', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'multipart/form-data; boundary=---------------------------408978034223735423202150501179', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 401}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/login", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 140094664083136, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 08:00:21.045266+00:00", "timestamp": 1758614421.045266}}}
{"text": "September 23, 2025 > 08:00:46 | INFO | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:00:38.881954", "seconds": 38.881954}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '53', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'application/json', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 409}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 140094664083136, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 08:00:46.114035+00:00", "timestamp": 1758614446.114035}}}
{"text": "September 23, 2025 > 08:03:35 | INFO | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:00:21.501471", "seconds": 21.501471}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '50', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'application/json', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 409}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 140228373751488, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 08:03:35.560372+00:00", "timestamp": 1758614615.560372}}}
{"text": "September 23, 2025 > 08:05:46 | INFO | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:00:09.906257", "seconds": 9.906257}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '50', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'application/json', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 409}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 140663116420800, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 08:05:46.658887+00:00", "timestamp": 1758614746.658887}}}
{"text": "September 23, 2025 > 08:07:11 | INFO | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:00:15.911594", "seconds": 15.911594}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '50', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'application/json', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 409}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 139685592921792, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 08:07:11.290452+00:00", "timestamp": 1758614831.290452}}}
{"text": "September 23, 2025 > 08:08:14 | INFO | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:00:10.519264", "seconds": 10.519264}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '50', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'application/json', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 409}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 11, "name": "SpawnProcess-1"}, "thread": {"id": 140223799187136, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 08:08:14.635865+00:00", "timestamp": 1758614894.635865}}}
{"text": "September 23, 2025 > 08:12:06 | INFO | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:04:02.749019", "seconds": 242.749019}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '50', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'application/json', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 409}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 11, "name": "SpawnProcess-1"}, "thread": {"id": 140223799187136, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 08:12:06.865620+00:00", "timestamp": 1758615126.86562}}}
{"text": "September 23, 2025 > 08:13:41 | INFO | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:00:08.298183", "seconds": 8.298183}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '50', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'application/json', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 409}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 139670163097280, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 08:13:41.848416+00:00", "timestamp": 1758615221.848416}}}
{"text": "September 23, 2025 > 08:16:42 | INFO | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:00:07.035117", "seconds": 7.035117}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '50', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'application/json', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 409}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 139728605152960, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 08:16:42.354554+00:00", "timestamp": 1758615402.354554}}}
{"text": "September 23, 2025 > 08:17:39 | INFO | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:00:07.634413", "seconds": 7.634413}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '50', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'application/json', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 409}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 140080332068544, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 08:17:39.527277+00:00", "timestamp": 1758615459.527277}}}
{"text": "September 23, 2025 > 08:18:25 | INFO | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:00:09.248536", "seconds": 9.248536}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '50', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'application/json', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 409}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 140583625656000, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 08:18:25.462199+00:00", "timestamp": 1758615505.462199}}}
{"text": "September 23, 2025 > 08:20:56 | INFO | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:00:10.444266", "seconds": 10.444266}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '50', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'application/json', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 409}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 140077102692032, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 08:20:56.803447+00:00", "timestamp": 1758615656.803447}}}
{"text": "September 23, 2025 > 08:30:30 | INFO | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:00:22.798897", "seconds": 22.798897}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '81', 'user-agent': 'curl/7.81.0', 'accept': '*/*', 'content-type': 'application/json'})", "method": "POST"}, "res": {"status_code": 409}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 20, "name": "SpawnProcess-2"}, "thread": {"id": 140439101548224, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 08:30:30.720223+00:00", "timestamp": 1758616230.720223}}}
{"text": "September 23, 2025 > 08:30:45 | INFO | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:00:03.012830", "seconds": 3.01283}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '81', 'user-agent': 'curl/7.81.0', 'accept': '*/*', 'content-type': 'application/json'})", "method": "POST"}, "res": {"status_code": 409}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 27, "name": "SpawnProcess-3"}, "thread": {"id": 139766753302208, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 08:30:45.626595+00:00", "timestamp": 1758616245.626595}}}
{"text": "September 23, 2025 > 08:31:49 | INFO | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:00:03.981619", "seconds": 3.981619}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '81', 'user-agent': 'curl/7.81.0', 'accept': '*/*', 'content-type': 'application/json'})", "method": "POST"}, "res": {"status_code": 409}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 36, "name": "SpawnProcess-5"}, "thread": {"id": 140473068381888, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 08:31:49.710791+00:00", "timestamp": 1758616309.710791}}}
{"text": "September 23, 2025 > 08:33:42 | ERROR | User 'testuser' already exists\n  + Exception Group Traceback (most recent call last):\n  |\n  |   File \"/app/.venv/lib/python3.11/site-packages/starlette/_utils.py\", line 79, in collapse_excgroups\n  |     yield\n  |   File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 183, in __call__\n  |     async with anyio.create_task_group() as task_group:\n  |                │     │                      └ <anyio._backends._asyncio.TaskGroup object at 0x7f897fd99790>\n  |                │     └ <function create_task_group at 0x7f8982569620>\n  |                └ <module 'anyio' from '/app/.venv/lib/python3.11/site-packages/anyio/__init__.py'>\n  |   File \"/app/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py\", line 772, in __aexit__\n  |     raise BaseExceptionGroup(\n  |\n  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py\", line 164, in __call__\n    |     await self.app(scope, receive, _send)\n    |           │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7f897fd85580>\n    |           │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f897fd...\n    |           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n    |           │    └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f897fef4cd0>\n    |           └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f898034b390>\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 182, in __call__\n    |     with recv_stream, send_stream, collapse_excgroups():\n    |          │            │            └ <function collapse_excgroups at 0x7f8981644cc0>\n    |          │            └ MemoryObjectSendStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_receive...\n    |          └ MemoryObjectReceiveStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_rece...\n    |   File \"/usr/local/lib/python3.11/contextlib.py\", line 158, in __exit__\n    |     self.gen.throw(typ, value, traceback)\n    |     │    │   │     │    │      └ <traceback object at 0x7f897fe140c0>\n    |     │    │   │     │    └ ExceptionGroup('unhandled errors in a TaskGroup', [UserAlreadyExistsException(\"User 'testuser' already exists\")])\n    |     │    │   │     └ <class 'ExceptionGroup'>\n    |     │    │   └ <method 'throw' of 'generator' objects>\n    |     │    └ <generator object collapse_excgroups at 0x7f897fd8d1c0>\n    |     └ <contextlib._GeneratorContextManager object at 0x7f897fdd0e50>\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/_utils.py\", line 85, in collapse_excgroups\n    |     raise exc\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 184, in __call__\n    |     response = await self.dispatch_func(request, call_next)\n    |                      │    │             │        └ <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x7f897fd85620>\n    |                      │    │             └ <starlette.middleware.base._CachedRequest object at 0x7f897fd99e50>\n    |                      │    └ <function setup_fastapi_logging.<locals>.log_request at 0x7f897fd84b80>\n    |                      └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f897fef4cd0>\n    |\n    |   File \"/app/src/core/logging_setup.py\", line 53, in log_request\n    |     response: Response = await call_next(request)\n    |                                │         └ <starlette.middleware.base._CachedRequest object at 0x7f897fd99e50>\n    |                                └ <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x7f897fd85620>\n    |\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 159, in call_next\n    |     raise app_exc\n    |           └ UserAlreadyExistsException(\"User 'testuser' already exists\")\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 144, in coro\n    |     await self.app(scope, receive_or_disconnect, send_no_error)\n    |           │    │   │      │                      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.send_no_error at 0x7f897ff07c40>\n    |           │    │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f897fd86520>\n    |           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n    |           │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f897fef4e90>\n    |           └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f897fef4cd0>\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py\", line 63, in __call__\n    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n    |           │                            │    │    │     │      │        └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.send_no_error at 0x7f897ff07c40>\n    |           │                            │    │    │     │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f897fd86520>\n    |           │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n    |           │                            │    │    └ <starlette.requests.Request object at 0x7f897fd9a090>\n    |           │                            │    └ <fastapi.routing.APIRouter object at 0x7f897fd81c10>\n    |           │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f897fef4e90>\n    |           └ <function wrap_app_handling_exceptions at 0x7f89814c7600>\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |           │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7f897fde7b00>\n    |           │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f897fd86520>\n    |           │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n    |           └ <fastapi.routing.APIRouter object at 0x7f897fd81c10>\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 716, in __call__\n    |     await self.middleware_stack(scope, receive, send)\n    |           │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7f897fde7b00>\n    |           │    │                │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f897fd86520>\n    |           │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n    |           │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x7f897fd81c10>>\n    |           └ <fastapi.routing.APIRouter object at 0x7f897fd81c10>\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 736, in app\n    |     await route.handle(scope, receive, send)\n    |           │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7f897fde7b00>\n    |           │     │      │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f897fd86520>\n    |           │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n    |           │     └ <function Route.handle at 0x7f89814ecc20>\n    |           └ APIRoute(path='/backend/auth/register', name='register_account', methods=['POST'])\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 290, in handle\n    |     await self.app(scope, receive, send)\n    |           │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7f897fde7b00>\n    |           │    │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f897fd86520>\n    |           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n    |           │    └ <function request_response.<locals>.app at 0x7f897fd84d60>\n    |           └ APIRoute(path='/backend/auth/register', name='register_account', methods=['POST'])\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 78, in app\n    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n    |           │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7f897fde7b00>\n    |           │                            │    │        │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f897fd86520>\n    |           │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n    |           │                            │    └ <starlette.requests.Request object at 0x7f897fd9a4d0>\n    |           │                            └ <function request_response.<locals>.app.<locals>.app at 0x7f897fde7ba0>\n    |           └ <function wrap_app_handling_exceptions at 0x7f89814c7600>\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |           │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7f897fde7ce0>\n    |           │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f897fd86520>\n    |           │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n    |           └ <function request_response.<locals>.app.<locals>.app at 0x7f897fde7ba0>\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 75, in app\n    |     response = await f(request)\n    |                      │ └ <starlette.requests.Request object at 0x7f897fd9a4d0>\n    |                      └ <function get_request_handler.<locals>.app at 0x7f897fd84ae0>\n    |   File \"/app/.venv/lib/python3.11/site-packages/fastapi/routing.py\", line 308, in app\n    |     raw_response = await run_endpoint_function(\n    |                          └ <function run_endpoint_function at 0x7f89814ec720>\n    |   File \"/app/.venv/lib/python3.11/site-packages/fastapi/routing.py\", line 219, in run_endpoint_function\n    |     return await dependant.call(**values)\n    |                  │         │      └ {'auth_uow': <src.auth.infrastructure.db.unit_of_work.PGAuthUnitOfWork object at 0x7f8981fe1950>, 'password_helper': <src.aut...\n    |                  │         └ <function register_account at 0x7f89814f8040>\n    |                  └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[ModelField(field_info=Body(Pydant...\n    |\n    |   File \"/app/src/auth/api/rest.py\", line 20, in register_account\n    |     return await RegisterUseCase(auth_uow, password_helper, auth_provider).execute(dto)\n    |                  │               │         │                │                      └ RegisterDTO(name='testuser', password='password123', attributes=[])\n    |                  │               │         │                └ <src.auth.infrastructure.jwt_auth_provider.JWTAuthProvider object at 0x7f897fdedad0>\n    |                  │               │         └ <src.auth.infrastructure.password_helper.PasswordHelper object at 0x7f897fded8d0>\n    |                  │               └ <src.auth.infrastructure.db.unit_of_work.PGAuthUnitOfWork object at 0x7f8981fe1950>\n    |                  └ <class 'src.auth.application.use_cases.register.RegisterUseCase'>\n    |\n    |   File \"/app/src/auth/application/use_cases/register.py\", line 27, in execute\n    |     raise UserAlreadyExistsException(dto.name)\n    |           │                          │   └ 'testuser'\n    |           │                          └ RegisterDTO(name='testuser', password='password123', attributes=[])\n    |           └ <class 'src.auth.exceptions.UserAlreadyExistsException'>\n    |\n    | src.auth.exceptions.UserAlreadyExistsException: User 'testuser' already exists\n    +------------------------------------\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n  File \"/usr/local/lib/python3.11/multiprocessing/spawn.py\", line 122, in spawn_main\n    exitcode = _main(fd, parent_sentinel)\n               │     │   └ 4\n               │     └ 10\n               └ <function _main at 0x7f898373d6c0>\n  File \"/usr/local/lib/python3.11/multiprocessing/spawn.py\", line 135, in _main\n    return self._bootstrap(parent_sentinel)\n           │    │          └ 4\n           │    └ <function BaseProcess._bootstrap at 0x7f898381eca0>\n           └ <SpawnProcess name='SpawnProcess-10' parent=10 started>\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n    │    └ <function BaseProcess.run at 0x7f898381e200>\n    └ <SpawnProcess name='SpawnProcess-10' parent=10 started>\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x7f89834e3290>, 'target': <bound method Server.run of <uvicorn.server.Server obj...\n    │    │        │    │        └ <SpawnProcess name='SpawnProcess-10' parent=10 started>\n    │    │        │    └ ()\n    │    │        └ <SpawnProcess name='SpawnProcess-10' parent=10 started>\n    │    └ <function subprocess_started at 0x7f89826ce480>\n    └ <SpawnProcess name='SpawnProcess-10' parent=10 started>\n  File \"/app/.venv/lib/python3.11/site-packages/uvicorn/_subprocess.py\", line 80, in subprocess_started\n    target(sockets=sockets)\n    │              └ [<socket.socket fd=3, family=2, type=1, proto=0, laddr=('0.0.0.0', 8000)>]\n    └ <bound method Server.run of <uvicorn.server.Server object at 0x7f89826241d0>>\n  File \"/app/.venv/lib/python3.11/site-packages/uvicorn/server.py\", line 67, in run\n    return asyncio_run(self.serve(sockets=sockets), loop_factory=self.config.get_loop_factory())\n           │           │    │             │                      │    │      └ <function Config.get_loop_factory at 0x7f8982855440>\n           │           │    │             │                      │    └ <uvicorn.config.Config object at 0x7f89834e3290>\n           │           │    │             │                      └ <uvicorn.server.Server object at 0x7f89826241d0>\n           │           │    │             └ [<socket.socket fd=3, family=2, type=1, proto=0, laddr=('0.0.0.0', 8000)>]\n           │           │    └ <function Server.serve at 0x7f89826cd260>\n           │           └ <uvicorn.server.Server object at 0x7f89826241d0>\n           └ <function asyncio_run at 0x7f89826cd120>\n  File \"/app/.venv/lib/python3.11/site-packages/uvicorn/_compat.py\", line 23, in asyncio_run\n    return runner.run(main)\n           │      │   └ <coroutine object Server.serve at 0x7f89836a2980>\n           │      └ <function Runner.run at 0x7f8982aa65c0>\n           └ <asyncio.runners.Runner object at 0x7f8983733810>\n  File \"/usr/local/lib/python3.11/asyncio/runners.py\", line 118, in run\n    return self._loop.run_until_complete(task)\n           │    │     │                  └ <Task pending name='Task-1' coro=<Server.serve() running at /app/.venv/lib/python3.11/site-packages/uvicorn/server.py:71> wai...\n           │    │     └ <cyfunction Loop.run_until_complete at 0x7f8982190fb0>\n           │    └ <uvloop.Loop running=True closed=False debug=False>\n           └ <asyncio.runners.Runner object at 0x7f8983733810>\n  File \"/app/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py\", line 409, in run_asgi\n    result = await app(  # type: ignore[func-returns-value]\n                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f8982195510>\n  File \"/app/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py\", line 60, in __call__\n    return await self.app(scope, receive, send)\n                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f897fd99d...\n                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f897fd...\n                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n                 │    └ <fastapi.applications.FastAPI object at 0x7f898209e3d0>\n                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7f8982195510>\n  File \"/app/.venv/lib/python3.11/site-packages/fastapi/applications.py\", line 1082, in __call__\n    await super().__call__(scope, receive, send)\n                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f897fd99d...\n                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f897fd...\n                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/applications.py\", line 113, in __call__\n    await self.middleware_stack(scope, receive, send)\n          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f897fd99d...\n          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f897fd...\n          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f898034b390>\n          └ <fastapi.applications.FastAPI object at 0x7f898209e3d0>\n> File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py\", line 164, in __call__\n    await self.app(scope, receive, _send)\n          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7f897fd85580>\n          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7f897fd...\n          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          │    └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f897fef4cd0>\n          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7f898034b390>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 182, in __call__\n    with recv_stream, send_stream, collapse_excgroups():\n         │            │            └ <function collapse_excgroups at 0x7f8981644cc0>\n         │            └ MemoryObjectSendStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_receive...\n         └ MemoryObjectReceiveStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_rece...\n  File \"/usr/local/lib/python3.11/contextlib.py\", line 158, in __exit__\n    self.gen.throw(typ, value, traceback)\n    │    │   │     │    │      └ <traceback object at 0x7f897fe140c0>\n    │    │   │     │    └ ExceptionGroup('unhandled errors in a TaskGroup', [UserAlreadyExistsException(\"User 'testuser' already exists\")])\n    │    │   │     └ <class 'ExceptionGroup'>\n    │    │   └ <method 'throw' of 'generator' objects>\n    │    └ <generator object collapse_excgroups at 0x7f897fd8d1c0>\n    └ <contextlib._GeneratorContextManager object at 0x7f897fdd0e50>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/_utils.py\", line 85, in collapse_excgroups\n    raise exc\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 184, in __call__\n    response = await self.dispatch_func(request, call_next)\n                     │    │             │        └ <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x7f897fd85620>\n                     │    │             └ <starlette.middleware.base._CachedRequest object at 0x7f897fd99e50>\n                     │    └ <function setup_fastapi_logging.<locals>.log_request at 0x7f897fd84b80>\n                     └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f897fef4cd0>\n\n  File \"/app/src/core/logging_setup.py\", line 53, in log_request\n    response: Response = await call_next(request)\n                               │         └ <starlette.middleware.base._CachedRequest object at 0x7f897fd99e50>\n                               └ <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x7f897fd85620>\n\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 159, in call_next\n    raise app_exc\n          └ UserAlreadyExistsException(\"User 'testuser' already exists\")\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n          │    │   │      │                      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.send_no_error at 0x7f897ff07c40>\n          │    │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f897fd86520>\n          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f897fef4e90>\n          └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7f897fef4cd0>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n          │                            │    │    │     │      │        └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.send_no_error at 0x7f897ff07c40>\n          │                            │    │    │     │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f897fd86520>\n          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          │                            │    │    └ <starlette.requests.Request object at 0x7f897fd9a090>\n          │                            │    └ <fastapi.routing.APIRouter object at 0x7f897fd81c10>\n          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7f897fef4e90>\n          └ <function wrap_app_handling_exceptions at 0x7f89814c7600>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7f897fde7b00>\n          │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f897fd86520>\n          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          └ <fastapi.routing.APIRouter object at 0x7f897fd81c10>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7f897fde7b00>\n          │    │                │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f897fd86520>\n          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x7f897fd81c10>>\n          └ <fastapi.routing.APIRouter object at 0x7f897fd81c10>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7f897fde7b00>\n          │     │      │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f897fd86520>\n          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          │     └ <function Route.handle at 0x7f89814ecc20>\n          └ APIRoute(path='/backend/auth/register', name='register_account', methods=['POST'])\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7f897fde7b00>\n          │    │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f897fd86520>\n          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          │    └ <function request_response.<locals>.app at 0x7f897fd84d60>\n          └ APIRoute(path='/backend/auth/register', name='register_account', methods=['POST'])\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7f897fde7b00>\n          │                            │    │        │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f897fd86520>\n          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          │                            │    └ <starlette.requests.Request object at 0x7f897fd9a4d0>\n          │                            └ <function request_response.<locals>.app.<locals>.app at 0x7f897fde7ba0>\n          └ <function wrap_app_handling_exceptions at 0x7f89814c7600>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7f897fde7ce0>\n          │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7f897fd86520>\n          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          └ <function request_response.<locals>.app.<locals>.app at 0x7f897fde7ba0>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 75, in app\n    response = await f(request)\n                     │ └ <starlette.requests.Request object at 0x7f897fd9a4d0>\n                     └ <function get_request_handler.<locals>.app at 0x7f897fd84ae0>\n  File \"/app/.venv/lib/python3.11/site-packages/fastapi/routing.py\", line 308, in app\n    raw_response = await run_endpoint_function(\n                         └ <function run_endpoint_function at 0x7f89814ec720>\n  File \"/app/.venv/lib/python3.11/site-packages/fastapi/routing.py\", line 219, in run_endpoint_function\n    return await dependant.call(**values)\n                 │         │      └ {'auth_uow': <src.auth.infrastructure.db.unit_of_work.PGAuthUnitOfWork object at 0x7f8981fe1950>, 'password_helper': <src.aut...\n                 │         └ <function register_account at 0x7f89814f8040>\n                 └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[ModelField(field_info=Body(Pydant...\n\n  File \"/app/src/auth/api/rest.py\", line 20, in register_account\n    return await RegisterUseCase(auth_uow, password_helper, auth_provider).execute(dto)\n                 │               │         │                │                      └ RegisterDTO(name='testuser', password='password123', attributes=[])\n                 │               │         │                └ <src.auth.infrastructure.jwt_auth_provider.JWTAuthProvider object at 0x7f897fdedad0>\n                 │               │         └ <src.auth.infrastructure.password_helper.PasswordHelper object at 0x7f897fded8d0>\n                 │               └ <src.auth.infrastructure.db.unit_of_work.PGAuthUnitOfWork object at 0x7f8981fe1950>\n                 └ <class 'src.auth.application.use_cases.register.RegisterUseCase'>\n\n  File \"/app/src/auth/application/use_cases/register.py\", line 27, in execute\n    raise UserAlreadyExistsException(dto.name)\n          │                          │   └ 'testuser'\n          │                          └ RegisterDTO(name='testuser', password='password123', attributes=[])\n          └ <class 'src.auth.exceptions.UserAlreadyExistsException'>\n\nsrc.auth.exceptions.UserAlreadyExistsException: User 'testuser' already exists\n", "record": {"elapsed": {"repr": "0:00:13.586282", "seconds": 13.586282}, "exception": {"type": "UserAlreadyExistsException", "value": "User 'testuser' already exists", "traceback": true}, "extra": {"name": "fastapi", "app_name": "Pool"}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log_exceptions", "level": {"icon": "❌", "name": "ERROR", "no": 40}, "line": 59, "message": "User 'testuser' already exists", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 51, "name": "SpawnProcess-10"}, "thread": {"id": 140228595682176, "name": "MainThread"}, "time": {"repr": "2025-09-23 08:33:42.681765+00:00", "timestamp": 1758616422.681765}}}
{"text": "September 23, 2025 > 08:34:35 | ERROR | User 'testuser' already exists\n  + Exception Group Traceback (most recent call last):\n  |\n  |   File \"/app/.venv/lib/python3.11/site-packages/starlette/_utils.py\", line 79, in collapse_excgroups\n  |     yield\n  |   File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 183, in __call__\n  |     async with anyio.create_task_group() as task_group:\n  |                │     │                      └ <anyio._backends._asyncio.TaskGroup object at 0x7fbd7889ded0>\n  |                │     └ <function create_task_group at 0x7fbd7aea5620>\n  |                └ <module 'anyio' from '/app/.venv/lib/python3.11/site-packages/anyio/__init__.py'>\n  |   File \"/app/.venv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py\", line 772, in __aexit__\n  |     raise BaseExceptionGroup(\n  |\n  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)\n  +-+---------------- 1 ----------------\n    | Traceback (most recent call last):\n    |\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py\", line 164, in __call__\n    |     await self.app(scope, receive, _send)\n    |           │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7fbd78889580>\n    |           │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fbd788...\n    |           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n    |           │    └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7fbd78c5b090>\n    |           └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7fbd78b6f990>\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 182, in __call__\n    |     with recv_stream, send_stream, collapse_excgroups():\n    |          │            │            └ <function collapse_excgroups at 0x7fbd79f84cc0>\n    |          │            └ MemoryObjectSendStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_receive...\n    |          └ MemoryObjectReceiveStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_rece...\n    |   File \"/usr/local/lib/python3.11/contextlib.py\", line 158, in __exit__\n    |     self.gen.throw(typ, value, traceback)\n    |     │    │   │     │    │      └ <traceback object at 0x7fbd78718ec0>\n    |     │    │   │     │    └ ExceptionGroup('unhandled errors in a TaskGroup', [UserAlreadyExistsException(\"User 'testuser' already exists\")])\n    |     │    │   │     └ <class 'ExceptionGroup'>\n    |     │    │   └ <method 'throw' of 'generator' objects>\n    |     │    └ <generator object collapse_excgroups at 0x7fbd788911c0>\n    |     └ <contextlib._GeneratorContextManager object at 0x7fbd78bb5a50>\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/_utils.py\", line 85, in collapse_excgroups\n    |     raise exc\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 184, in __call__\n    |     response = await self.dispatch_func(request, call_next)\n    |                      │    │             │        └ <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x7fbd78889620>\n    |                      │    │             └ <starlette.middleware.base._CachedRequest object at 0x7fbd7889de90>\n    |                      │    └ <function setup_fastapi_logging.<locals>.log_request at 0x7fbd78888b80>\n    |                      └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7fbd78c5b090>\n    |\n    |   File \"/app/src/core/logging_setup.py\", line 53, in log_request\n    |     response: Response = await call_next(request)\n    |                                │         └ <starlette.middleware.base._CachedRequest object at 0x7fbd7889de90>\n    |                                └ <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x7fbd78889620>\n    |\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 159, in call_next\n    |     raise app_exc\n    |           └ UserAlreadyExistsException(\"User 'testuser' already exists\")\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 144, in coro\n    |     await self.app(scope, receive_or_disconnect, send_no_error)\n    |           │    │   │      │                      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.send_no_error at 0x7fbd7880fc40>\n    |           │    │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7fbd7888a520>\n    |           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n    |           │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7fbd787fd210>\n    |           └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7fbd78c5b090>\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py\", line 63, in __call__\n    |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n    |           │                            │    │    │     │      │        └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.send_no_error at 0x7fbd7880fc40>\n    |           │                            │    │    │     │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7fbd7888a520>\n    |           │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n    |           │                            │    │    └ <starlette.requests.Request object at 0x7fbd7889e550>\n    |           │                            │    └ <fastapi.routing.APIRouter object at 0x7fbd78882150>\n    |           │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7fbd787fd210>\n    |           └ <function wrap_app_handling_exceptions at 0x7fbd79e07600>\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |           │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7fbd786ebb00>\n    |           │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7fbd7888a520>\n    |           │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n    |           └ <fastapi.routing.APIRouter object at 0x7fbd78882150>\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 716, in __call__\n    |     await self.middleware_stack(scope, receive, send)\n    |           │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7fbd786ebb00>\n    |           │    │                │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7fbd7888a520>\n    |           │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n    |           │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x7fbd78882150>>\n    |           └ <fastapi.routing.APIRouter object at 0x7fbd78882150>\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 736, in app\n    |     await route.handle(scope, receive, send)\n    |           │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7fbd786ebb00>\n    |           │     │      │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7fbd7888a520>\n    |           │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n    |           │     └ <function Route.handle at 0x7fbd79e2cc20>\n    |           └ APIRoute(path='/backend/auth/register', name='register_account', methods=['POST'])\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 290, in handle\n    |     await self.app(scope, receive, send)\n    |           │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7fbd786ebb00>\n    |           │    │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7fbd7888a520>\n    |           │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n    |           │    └ <function request_response.<locals>.app at 0x7fbd78888d60>\n    |           └ APIRoute(path='/backend/auth/register', name='register_account', methods=['POST'])\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 78, in app\n    |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n    |           │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7fbd786ebb00>\n    |           │                            │    │        │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7fbd7888a520>\n    |           │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n    |           │                            │    └ <starlette.requests.Request object at 0x7fbd78880b10>\n    |           │                            └ <function request_response.<locals>.app.<locals>.app at 0x7fbd786ebba0>\n    |           └ <function wrap_app_handling_exceptions at 0x7fbd79e07600>\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    |     raise exc\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    |     await app(scope, receive, sender)\n    |           │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7fbd786ebce0>\n    |           │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7fbd7888a520>\n    |           │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n    |           └ <function request_response.<locals>.app.<locals>.app at 0x7fbd786ebba0>\n    |   File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 75, in app\n    |     response = await f(request)\n    |                      │ └ <starlette.requests.Request object at 0x7fbd78880b10>\n    |                      └ <function get_request_handler.<locals>.app at 0x7fbd78888ae0>\n    |   File \"/app/.venv/lib/python3.11/site-packages/fastapi/routing.py\", line 308, in app\n    |     raw_response = await run_endpoint_function(\n    |                          └ <function run_endpoint_function at 0x7fbd79e2c720>\n    |   File \"/app/.venv/lib/python3.11/site-packages/fastapi/routing.py\", line 219, in run_endpoint_function\n    |     return await dependant.call(**values)\n    |                  │         │      └ {'auth_uow': <src.auth.infrastructure.db.unit_of_work.PGAuthUnitOfWork object at 0x7fbd78dd8950>, 'password_helper': <src.aut...\n    |                  │         └ <function register_account at 0x7fbd79e38040>\n    |                  └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[ModelField(field_info=Body(Pydant...\n    |\n    |   File \"/app/src/auth/api/rest.py\", line 20, in register_account\n    |     return await RegisterUseCase(auth_uow, password_helper, auth_provider).execute(dto)\n    |                  │               │         │                │                      └ RegisterDTO(name='testuser', password='password123', attributes=[])\n    |                  │               │         │                └ <src.auth.infrastructure.jwt_auth_provider.JWTAuthProvider object at 0x7fbd786f1c90>\n    |                  │               │         └ <src.auth.infrastructure.password_helper.PasswordHelper object at 0x7fbd786f1b50>\n    |                  │               └ <src.auth.infrastructure.db.unit_of_work.PGAuthUnitOfWork object at 0x7fbd78dd8950>\n    |                  └ <class 'src.auth.application.use_cases.register.RegisterUseCase'>\n    |\n    |   File \"/app/src/auth/application/use_cases/register.py\", line 27, in execute\n    |     raise UserAlreadyExistsException(dto.name)\n    |           │                          │   └ 'testuser'\n    |           │                          └ RegisterDTO(name='testuser', password='password123', attributes=[])\n    |           └ <class 'src.auth.exceptions.UserAlreadyExistsException'>\n    |\n    | src.auth.exceptions.UserAlreadyExistsException: User 'testuser' already exists\n    +------------------------------------\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n  File \"<string>\", line 1, in <module>\n  File \"/usr/local/lib/python3.11/multiprocessing/spawn.py\", line 122, in spawn_main\n    exitcode = _main(fd, parent_sentinel)\n               │     │   └ 4\n               │     └ 10\n               └ <function _main at 0x7fbd7c0856c0>\n  File \"/usr/local/lib/python3.11/multiprocessing/spawn.py\", line 135, in _main\n    return self._bootstrap(parent_sentinel)\n           │    │          └ 4\n           │    └ <function BaseProcess._bootstrap at 0x7fbd7c166ca0>\n           └ <SpawnProcess name='SpawnProcess-11' parent=10 started>\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n    │    └ <function BaseProcess.run at 0x7fbd7c166200>\n    └ <SpawnProcess name='SpawnProcess-11' parent=10 started>\n  File \"/usr/local/lib/python3.11/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n    │    │        │    │        │    └ {'config': <uvicorn.config.Config object at 0x7fbd7be2b2d0>, 'target': <bound method Server.run of <uvicorn.server.Server obj...\n    │    │        │    │        └ <SpawnProcess name='SpawnProcess-11' parent=10 started>\n    │    │        │    └ ()\n    │    │        └ <SpawnProcess name='SpawnProcess-11' parent=10 started>\n    │    └ <function subprocess_started at 0x7fbd7b00a480>\n    └ <SpawnProcess name='SpawnProcess-11' parent=10 started>\n  File \"/app/.venv/lib/python3.11/site-packages/uvicorn/_subprocess.py\", line 80, in subprocess_started\n    target(sockets=sockets)\n    │              └ [<socket.socket fd=3, family=2, type=1, proto=0, laddr=('0.0.0.0', 8000)>]\n    └ <bound method Server.run of <uvicorn.server.Server object at 0x7fbd7af602d0>>\n  File \"/app/.venv/lib/python3.11/site-packages/uvicorn/server.py\", line 67, in run\n    return asyncio_run(self.serve(sockets=sockets), loop_factory=self.config.get_loop_factory())\n           │           │    │             │                      │    │      └ <function Config.get_loop_factory at 0x7fbd7b191440>\n           │           │    │             │                      │    └ <uvicorn.config.Config object at 0x7fbd7be2b2d0>\n           │           │    │             │                      └ <uvicorn.server.Server object at 0x7fbd7af602d0>\n           │           │    │             └ [<socket.socket fd=3, family=2, type=1, proto=0, laddr=('0.0.0.0', 8000)>]\n           │           │    └ <function Server.serve at 0x7fbd7b009260>\n           │           └ <uvicorn.server.Server object at 0x7fbd7af602d0>\n           └ <function asyncio_run at 0x7fbd7b009120>\n  File \"/app/.venv/lib/python3.11/site-packages/uvicorn/_compat.py\", line 23, in asyncio_run\n    return runner.run(main)\n           │      │   └ <coroutine object Server.serve at 0x7fbd7bfea980>\n           │      └ <function Runner.run at 0x7fbd7b3e65c0>\n           └ <asyncio.runners.Runner object at 0x7fbd7b1bb8d0>\n  File \"/usr/local/lib/python3.11/asyncio/runners.py\", line 118, in run\n    return self._loop.run_until_complete(task)\n           │    │     │                  └ <Task pending name='Task-1' coro=<Server.serve() running at /app/.venv/lib/python3.11/site-packages/uvicorn/server.py:71> wai...\n           │    │     └ <cyfunction Loop.run_until_complete at 0x7fbd7aaccfb0>\n           │    └ <uvloop.Loop running=True closed=False debug=False>\n           └ <asyncio.runners.Runner object at 0x7fbd7b1bb8d0>\n  File \"/app/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py\", line 409, in run_asgi\n    result = await app(  # type: ignore[func-returns-value]\n                   └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7fbd7aad1750>\n  File \"/app/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py\", line 60, in __call__\n    return await self.app(scope, receive, send)\n                 │    │   │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fbd7889dd...\n                 │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fbd788...\n                 │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n                 │    └ <fastapi.applications.FastAPI object at 0x7fbd78bb5b90>\n                 └ <uvicorn.middleware.proxy_headers.ProxyHeadersMiddleware object at 0x7fbd7aad1750>\n  File \"/app/.venv/lib/python3.11/site-packages/fastapi/applications.py\", line 1082, in __call__\n    await super().__call__(scope, receive, send)\n                           │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fbd7889dd...\n                           │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fbd788...\n                           └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/applications.py\", line 113, in __call__\n    await self.middleware_stack(scope, receive, send)\n          │    │                │      │        └ <bound method RequestResponseCycle.send of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fbd7889dd...\n          │    │                │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fbd788...\n          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          │    └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7fbd78b6f990>\n          └ <fastapi.applications.FastAPI object at 0x7fbd78bb5b90>\n> File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py\", line 164, in __call__\n    await self.app(scope, receive, _send)\n          │    │   │      │        └ <function ServerErrorMiddleware.__call__.<locals>._send at 0x7fbd78889580>\n          │    │   │      └ <bound method RequestResponseCycle.receive of <uvicorn.protocols.http.httptools_impl.RequestResponseCycle object at 0x7fbd788...\n          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          │    └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7fbd78c5b090>\n          └ <starlette.middleware.errors.ServerErrorMiddleware object at 0x7fbd78b6f990>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 182, in __call__\n    with recv_stream, send_stream, collapse_excgroups():\n         │            │            └ <function collapse_excgroups at 0x7fbd79f84cc0>\n         │            └ MemoryObjectSendStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_receive...\n         └ MemoryObjectReceiveStream(_state=MemoryObjectStreamState(max_buffer_size=0, buffer=deque([]), open_send_channels=0, open_rece...\n  File \"/usr/local/lib/python3.11/contextlib.py\", line 158, in __exit__\n    self.gen.throw(typ, value, traceback)\n    │    │   │     │    │      └ <traceback object at 0x7fbd78718ec0>\n    │    │   │     │    └ ExceptionGroup('unhandled errors in a TaskGroup', [UserAlreadyExistsException(\"User 'testuser' already exists\")])\n    │    │   │     └ <class 'ExceptionGroup'>\n    │    │   └ <method 'throw' of 'generator' objects>\n    │    └ <generator object collapse_excgroups at 0x7fbd788911c0>\n    └ <contextlib._GeneratorContextManager object at 0x7fbd78bb5a50>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/_utils.py\", line 85, in collapse_excgroups\n    raise exc\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 184, in __call__\n    response = await self.dispatch_func(request, call_next)\n                     │    │             │        └ <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x7fbd78889620>\n                     │    │             └ <starlette.middleware.base._CachedRequest object at 0x7fbd7889de90>\n                     │    └ <function setup_fastapi_logging.<locals>.log_request at 0x7fbd78888b80>\n                     └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7fbd78c5b090>\n\n  File \"/app/src/core/logging_setup.py\", line 53, in log_request\n    response: Response = await call_next(request)\n                               │         └ <starlette.middleware.base._CachedRequest object at 0x7fbd7889de90>\n                               └ <function BaseHTTPMiddleware.__call__.<locals>.call_next at 0x7fbd78889620>\n\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 159, in call_next\n    raise app_exc\n          └ UserAlreadyExistsException(\"User 'testuser' already exists\")\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py\", line 144, in coro\n    await self.app(scope, receive_or_disconnect, send_no_error)\n          │    │   │      │                      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.send_no_error at 0x7fbd7880fc40>\n          │    │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7fbd7888a520>\n          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          │    └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7fbd787fd210>\n          └ <starlette.middleware.base.BaseHTTPMiddleware object at 0x7fbd78c5b090>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py\", line 63, in __call__\n    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)\n          │                            │    │    │     │      │        └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.send_no_error at 0x7fbd7880fc40>\n          │                            │    │    │     │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7fbd7888a520>\n          │                            │    │    │     └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          │                            │    │    └ <starlette.requests.Request object at 0x7fbd7889e550>\n          │                            │    └ <fastapi.routing.APIRouter object at 0x7fbd78882150>\n          │                            └ <starlette.middleware.exceptions.ExceptionMiddleware object at 0x7fbd787fd210>\n          └ <function wrap_app_handling_exceptions at 0x7fbd79e07600>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7fbd786ebb00>\n          │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7fbd7888a520>\n          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          └ <fastapi.routing.APIRouter object at 0x7fbd78882150>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 716, in __call__\n    await self.middleware_stack(scope, receive, send)\n          │    │                │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7fbd786ebb00>\n          │    │                │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7fbd7888a520>\n          │    │                └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          │    └ <bound method Router.app of <fastapi.routing.APIRouter object at 0x7fbd78882150>>\n          └ <fastapi.routing.APIRouter object at 0x7fbd78882150>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 736, in app\n    await route.handle(scope, receive, send)\n          │     │      │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7fbd786ebb00>\n          │     │      │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7fbd7888a520>\n          │     │      └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          │     └ <function Route.handle at 0x7fbd79e2cc20>\n          └ APIRoute(path='/backend/auth/register', name='register_account', methods=['POST'])\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 290, in handle\n    await self.app(scope, receive, send)\n          │    │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7fbd786ebb00>\n          │    │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7fbd7888a520>\n          │    │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          │    └ <function request_response.<locals>.app at 0x7fbd78888d60>\n          └ APIRoute(path='/backend/auth/register', name='register_account', methods=['POST'])\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 78, in app\n    await wrap_app_handling_exceptions(app, request)(scope, receive, send)\n          │                            │    │        │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7fbd786ebb00>\n          │                            │    │        │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7fbd7888a520>\n          │                            │    │        └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          │                            │    └ <starlette.requests.Request object at 0x7fbd78880b10>\n          │                            └ <function request_response.<locals>.app.<locals>.app at 0x7fbd786ebba0>\n          └ <function wrap_app_handling_exceptions at 0x7fbd79e07600>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 53, in wrapped_app\n    raise exc\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py\", line 42, in wrapped_app\n    await app(scope, receive, sender)\n          │   │      │        └ <function wrap_app_handling_exceptions.<locals>.wrapped_app.<locals>.sender at 0x7fbd786ebce0>\n          │   │      └ <function BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.receive_or_disconnect at 0x7fbd7888a520>\n          │   └ {'type': 'http', 'asgi': {'version': '3.0', 'spec_version': '2.3'}, 'http_version': '1.0', 'server': ('172.22.0.3', 8000), 'c...\n          └ <function request_response.<locals>.app.<locals>.app at 0x7fbd786ebba0>\n  File \"/app/.venv/lib/python3.11/site-packages/starlette/routing.py\", line 75, in app\n    response = await f(request)\n                     │ └ <starlette.requests.Request object at 0x7fbd78880b10>\n                     └ <function get_request_handler.<locals>.app at 0x7fbd78888ae0>\n  File \"/app/.venv/lib/python3.11/site-packages/fastapi/routing.py\", line 308, in app\n    raw_response = await run_endpoint_function(\n                         └ <function run_endpoint_function at 0x7fbd79e2c720>\n  File \"/app/.venv/lib/python3.11/site-packages/fastapi/routing.py\", line 219, in run_endpoint_function\n    return await dependant.call(**values)\n                 │         │      └ {'auth_uow': <src.auth.infrastructure.db.unit_of_work.PGAuthUnitOfWork object at 0x7fbd78dd8950>, 'password_helper': <src.aut...\n                 │         └ <function register_account at 0x7fbd79e38040>\n                 └ Dependant(path_params=[], query_params=[], header_params=[], cookie_params=[], body_params=[ModelField(field_info=Body(Pydant...\n\n  File \"/app/src/auth/api/rest.py\", line 20, in register_account\n    return await RegisterUseCase(auth_uow, password_helper, auth_provider).execute(dto)\n                 │               │         │                │                      └ RegisterDTO(name='testuser', password='password123', attributes=[])\n                 │               │         │                └ <src.auth.infrastructure.jwt_auth_provider.JWTAuthProvider object at 0x7fbd786f1c90>\n                 │               │         └ <src.auth.infrastructure.password_helper.PasswordHelper object at 0x7fbd786f1b50>\n                 │               └ <src.auth.infrastructure.db.unit_of_work.PGAuthUnitOfWork object at 0x7fbd78dd8950>\n                 └ <class 'src.auth.application.use_cases.register.RegisterUseCase'>\n\n  File \"/app/src/auth/application/use_cases/register.py\", line 27, in execute\n    raise UserAlreadyExistsException(dto.name)\n          │                          │   └ 'testuser'\n          │                          └ RegisterDTO(name='testuser', password='password123', attributes=[])\n          └ <class 'src.auth.exceptions.UserAlreadyExistsException'>\n\nsrc.auth.exceptions.UserAlreadyExistsException: User 'testuser' already exists\n", "record": {"elapsed": {"repr": "0:00:03.730856", "seconds": 3.730856}, "exception": {"type": "UserAlreadyExistsException", "value": "User 'testuser' already exists", "traceback": true}, "extra": {"name": "fastapi", "app_name": "Pool"}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log_exceptions", "level": {"icon": "❌", "name": "ERROR", "no": 40}, "line": 59, "message": "User 'testuser' already exists", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 58, "name": "SpawnProcess-11"}, "thread": {"id": 140451809508224, "name": "MainThread"}, "time": {"repr": "2025-09-23 08:34:35.059640+00:00", "timestamp": 1758616475.05964}}}
{"text": "September 23, 2025 > 09:06:47 | DEBUG | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:32:15.786956", "seconds": 1935.786956}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '53', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'application/json', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 201}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "🐞", "name": "DEBUG", "no": 10}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 58, "name": "SpawnProcess-11"}, "thread": {"id": 140451745920704, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 09:06:47.115740+00:00", "timestamp": 1758618407.11574}}}
{"text": "September 23, 2025 > 09:06:58 | DEBUG | POST /backend/auth/login\n", "record": {"elapsed": {"repr": "0:32:26.971084", "seconds": 1946.971084}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/login", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '303', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'multipart/form-data; boundary=---------------------------349765834524130804292747557382', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 200}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "🐞", "name": "DEBUG", "no": 10}, "line": 49, "message": "POST /backend/auth/login", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 58, "name": "SpawnProcess-11"}, "thread": {"id": 140451745920704, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 09:06:58.299868+00:00", "timestamp": 1758618418.299868}}}
{"text": "September 23, 2025 > 09:07:16 | INFO | POST /backend/auth/login\n", "record": {"elapsed": {"repr": "0:32:45.233071", "seconds": 1965.233071}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/login", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '304', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'multipart/form-data; boundary=---------------------------388846143320666787611561413173', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 401}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/login", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 58, "name": "SpawnProcess-11"}, "thread": {"id": 140451745920704, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 09:07:16.561855+00:00", "timestamp": 1758618436.561855}}}
{"text": "September 23, 2025 > 09:11:35 | INFO | POST /backend/auth/login\n", "record": {"elapsed": {"repr": "0:00:06.502135", "seconds": 6.502135}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/login", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '300', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'multipart/form-data; boundary=---------------------------36276130661828548830772937170', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 401}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/login", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 140116145587904, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 09:11:35.885716+00:00", "timestamp": 1758618695.885716}}}
{"text": "September 23, 2025 > 09:18:50 | INFO | POST /backend/auth/login\n", "record": {"elapsed": {"repr": "0:00:05.941948", "seconds": 5.941948}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/login", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '300', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'multipart/form-data; boundary=---------------------------27161829828416866512932804066', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 401}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/login", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 139773761525440, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 09:18:50.759487+00:00", "timestamp": 1758619130.759487}}}
{"text": "September 23, 2025 > 09:18:58 | INFO | POST /backend/auth/login\n", "record": {"elapsed": {"repr": "0:00:13.945190", "seconds": 13.94519}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/login", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '303', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'multipart/form-data; boundary=---------------------------320117815537495844131561873228', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 401}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/login", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 139773761525440, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 09:18:58.762729+00:00", "timestamp": 1758619138.762729}}}
{"text": "September 23, 2025 > 09:19:07 | INFO | POST /backend/auth/login\n", "record": {"elapsed": {"repr": "0:00:22.360663", "seconds": 22.360663}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/login", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '300', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'multipart/form-data; boundary=---------------------------15054084083757732802958592414', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 401}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/login", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 139773761525440, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 09:19:07.178202+00:00", "timestamp": 1758619147.178202}}}
{"text": "September 23, 2025 > 09:22:01 | INFO | POST /backend/auth/login\n", "record": {"elapsed": {"repr": "0:00:03.493674", "seconds": 3.493674}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/login", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '300', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'multipart/form-data; boundary=---------------------------30407596771047740013299998786', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 401}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/login", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 140427209197248, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 09:22:01.903918+00:00", "timestamp": 1758619321.903918}}}
{"text": "September 23, 2025 > 09:22:44 | INFO | POST /backend/auth/login\n", "record": {"elapsed": {"repr": "0:00:45.920431", "seconds": 45.920431}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/login", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '294', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'multipart/form-data; boundary=---------------------------17028158736400150052880781395', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 401}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/login", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 140427209197248, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 09:22:44.330675+00:00", "timestamp": 1758619364.330675}}}
{"text": "September 23, 2025 > 09:26:23 | INFO | POST /backend/auth/login\n", "record": {"elapsed": {"repr": "0:00:04.937511", "seconds": 4.937511}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/login", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '297', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'multipart/form-data; boundary=---------------------------153515884013520975661732477569', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 401}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 49, "message": "POST /backend/auth/login", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 139795631175360, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 09:26:23.628544+00:00", "timestamp": 1758619583.628544}}}
{"text": "September 23, 2025 > 09:26:41 | DEBUG | POST /backend/auth/register\n", "record": {"elapsed": {"repr": "0:00:22.507003", "seconds": 22.507003}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/register", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '53', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'application/json', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 201}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "🐞", "name": "DEBUG", "no": 10}, "line": 49, "message": "POST /backend/auth/register", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 139795631175360, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 09:26:41.198036+00:00", "timestamp": 1758619601.198036}}}
{"text": "September 23, 2025 > 09:26:54 | DEBUG | POST /backend/auth/login\n", "record": {"elapsed": {"repr": "0:00:36.276792", "seconds": 36.276792}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/login", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '303', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'multipart/form-data; boundary=---------------------------215824035437038583021999666219', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 200}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "🐞", "name": "DEBUG", "no": 10}, "line": 49, "message": "POST /backend/auth/login", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 139795631175360, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 09:26:54.967825+00:00", "timestamp": 1758619614.967825}}}
{"text": "September 23, 2025 > 09:35:25 | DEBUG | POST /backend/auth/login\n", "record": {"elapsed": {"repr": "0:01:14.184718", "seconds": 74.184718}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/login", "headers": "Headers({'host': '192.168.0.13', 'x-real-ip': '192.168.0.13', 'x-forwarded-for': '192.168.0.13', 'x-forwarded-proto': 'http', 'connection': 'close', 'content-length': '303', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'accept': 'application/json, text/plain, */*', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept-encoding': 'gzip, deflate', 'content-type': 'multipart/form-data; boundary=---------------------------106704106927389957862848108397', 'origin': 'http://192.168.0.13:3000', 'referer': 'http://192.168.0.13:3000/', 'priority': 'u=0'})", "method": "POST"}, "res": {"status_code": 200}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "🐞", "name": "DEBUG", "no": 10}, "line": 49, "message": "POST /backend/auth/login", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 140262245050048, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 09:35:25.061247+00:00", "timestamp": 1758620125.061247}}}
{"text": "September 23, 2025 > 09:41:16 | DEBUG | POST /backend/auth/login\n", "record": {"elapsed": {"repr": "0:03:25.018866", "seconds": 205.018866}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/login", "headers": "Headers({'priority': 'u=0', 'referer': 'http://172.22.0.4:3000/', 'connection': 'close', 'origin': 'http://172.22.0.4:3000', 'content-length': '300', 'content-type': 'multipart/form-data; boundary=---------------------------47922265831699640961004045152', 'accept-encoding': 'gzip, deflate', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept': 'application/json, text/plain, */*', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'host': 'backend:8000'})", "method": "POST"}, "res": {"status_code": 200}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "🐞", "name": "DEBUG", "no": 10}, "line": 49, "message": "POST /backend/auth/login", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 140692995561152, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 09:41:16.521739+00:00", "timestamp": 1758620476.521739}}}
{"text": "September 23, 2025 > 10:09:40 | DEBUG | POST /backend/auth/login\n", "record": {"elapsed": {"repr": "0:31:49.357675", "seconds": 1909.357675}, "exception": null, "extra": {"name": "fastapi", "app_name": "Pool", "http": {"req": {"url": "/backend/auth/login", "headers": "Headers({'priority': 'u=0', 'referer': 'http://172.22.0.4:3000/', 'connection': 'close', 'origin': 'http://172.22.0.4:3000', 'content-length': '303', 'content-type': 'multipart/form-data; boundary=---------------------------307897002231336215761299312087', 'accept-encoding': 'gzip, deflate', 'accept-language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3', 'accept': 'application/json, text/plain, */*', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0', 'host': 'backend:8000'})", "method": "POST"}, "res": {"status_code": 200}}}, "file": {"name": "logging_setup.py", "path": "/app/src/core/logging_setup.py"}, "function": "log", "level": {"icon": "🐞", "name": "DEBUG", "no": 10}, "line": 49, "message": "POST /backend/auth/login", "module": "logging_setup", "name": "src.core.logging_setup", "process": {"id": 12, "name": "SpawnProcess-1"}, "thread": {"id": 140692995561152, "name": "AnyIO worker thread"}, "time": {"repr": "2025-09-23 10:09:40.860548+00:00", "timestamp": 1758622180.860548}}}
